

#GFG FIRST MODULE OBJECTIVE 

# A = int(input("enter"))
# B = int(input("enter"))

# m = 1

# for i in range(1,B):
#     k = A**i

#     if k <= B:  #
#         m = k
       
#     else:
#         break

# if (B - m)>(A**(i)-B): #
#     print(A**(i))
    
# else:
#     print(m)

# GIVEN TWO DIGIT NUMBER FIND THE SUM OF ITS DIGITS

# n = int(input("enter"))

# k = n // 10

# l = n - (k*10)

# print(k+l)

# THE NUMBER OF CATS AND HATS SHOULD BE EQUAL IN A STRIG

# x = input("enter ")

# i=0
# j=0
# for ''cat'' in str:
#       i+=1
# for 'hat' in str:
#       j+=1
# if i == j:
#     print(True)
# else:
#     print(False)

        
