####You are given a string str, you need to print True if cat and hat appear same number of times in str, 
####otherwise print False.

# x = str(input("ENTER"))
# i = 0
# j = 0
# i = x.count('cat')
# j = x.count('hat')

# if i == j:
#       print(True)
# else:
#       print(False)





####GIVEN A NON NEGATIVE NUMBER N ,PRINT TRUE IF WITHIN 2 OF A MULTIPLE OF 10
###ELSE PRINT FALSE , MEANS BELOW OR ABOVE WITHIN 2 LIMITS

# x = input("enter")

# k = N // 10
# k = k*10
# l = [0,1,2,8,9]
# if (max(N,k) - min(N,k)) in l:
#       print(True)
# else:
#       print(False)




######GIVEN 2 INTEGERS IF THEIR SUM LIES IN BETWEEN 20 AND 40 THEN RETURN THE SUM 
### ORELSE RETURN THE SUM OF THE TWO NUMBERS

# x = int(input('enter'))
# y = int(input('enter'))

# sum = A+B
    
# if sum>19 and sum<41:
#       print(42)
# else:
#       print(sum)




#**************#####3
## FOR  A STRING INPUT IF THE WORD doge APPEARS INCREMENT COUNT ,
# ## HERE THE LETTER G CAN BE REPLACED BY ANY LETTER FROM A-Z
# m = input("enter")
# import re
# s="do.e"  # CHECKS FOR D,O,E LEAVING THE g TERM
# k=re.findall(s,m)  # FINDALL RETURNS LIST CONTAINING ALL THE REQUIRED COUNTS
# print(len(k))             
            
## 
